AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: API Stage
  Tenant:
    Type: String
    Default: ic
    Description: API Stage

Resources:
  PlanningPokerDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Stage}_${Tenant}_planning_poker
      AttributeDefinitions:
        - AttributeName: "sprint_id"
          AttributeType: "S"
        - AttributeName: "task_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "sprint_id"
          KeyType: "HASH"
        - AttributeName: "task_id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST